#!/bin/bash

# Script to extract Warp Firebase ID token from macOS Keychain
# This token is used to authenticate with Warp's GraphQL API

set -e

echo "🔑 Warp Token Extractor"
echo "======================"
echo ""

# Check if running on macOS
if [[ "$OSTYPE" != "darwin"* ]]; then
    echo "❌ Error: This script only works on macOS"
    echo "   Warp stores tokens in the macOS Keychain"
    exit 1
fi

# Check if Warp is installed
if [ ! -d "/Applications/Warp.app" ]; then
    echo "❌ Error: Warp is not installed"
    echo "   Please install Warp from https://warp.dev"
    exit 1
fi

echo "✓ Warp is installed"

# Check if user is logged into Warp
echo ""
echo "Checking for Warp authentication..."

USER_DATA=$(security find-generic-password -s "dev.warp.Warp-Stable" -a "User" -w 2>/dev/null || echo "")

if [ -z "$USER_DATA" ]; then
    echo ""
    echo "❌ Error: No Warp authentication found in Keychain"
    echo ""
    echo "📝 Please do the following:"
    echo "   1. Open Warp terminal"
    echo "   2. Sign in to your Warp account (if not already signed in)"
    echo "   3. Wait a few seconds for authentication to complete"
    echo "   4. Run this script again"
    echo ""
    exit 1
fi

echo "✓ Warp authentication found"

# Parse the JSON and extract the Firebase ID token
ID_TOKEN=$(echo "$USER_DATA" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    print(data['id_token']['id_token'])
except:
    print('')
")

if [ -z "$ID_TOKEN" ]; then
    echo ""
    echo "❌ Error: Could not extract Firebase ID token"
    echo "   The token format may have changed"
    exit 1
fi

# Check if token is expired
EXPIRATION=$(echo "$USER_DATA" | python3 -c "
import sys, json
from datetime import datetime
try:
    data = json.load(sys.stdin)
    exp = data['id_token']['expiration_time']
    exp_dt = datetime.fromisoformat(exp.replace('Z', '+00:00'))
    now = datetime.now(exp_dt.tzinfo)
    print('expired' if exp_dt < now else 'valid')
    print(exp)
except:
    print('unknown')
    print('')
")

TOKEN_STATUS=$(echo "$EXPIRATION" | head -n 1)
EXPIRY_TIME=$(echo "$EXPIRATION" | tail -n 1)

echo "✓ Token extracted successfully"
echo ""

if [ "$TOKEN_STATUS" = "expired" ]; then
    echo "⚠️  Warning: Token is expired (expired at $EXPIRY_TIME)"
    echo "   Please open Warp and use it for a few seconds to refresh the token"
    echo ""
fi

# Determine where to save the token
ENV_FILE=".env"

if [ ! -f "$ENV_FILE" ]; then
    echo "Creating .env file..."
    touch "$ENV_FILE"
fi

# Check if WARP_TOKEN already exists in .env
if grep -q "^WARP_TOKEN=" "$ENV_FILE" 2>/dev/null; then
    echo "Updating existing WARP_TOKEN in $ENV_FILE..."
    # Use sed to replace the line (compatible with macOS)
    if [[ "$OSTYPE" == "darwin"* ]]; then
        sed -i '' "s|^WARP_TOKEN=.*|WARP_TOKEN=$ID_TOKEN|" "$ENV_FILE"
    else
        sed -i "s|^WARP_TOKEN=.*|WARP_TOKEN=$ID_TOKEN|" "$ENV_FILE"
    fi
else
    echo "Adding WARP_TOKEN to $ENV_FILE..."
    echo "" >> "$ENV_FILE"
    echo "# Warp.dev Firebase ID Token" >> "$ENV_FILE"
    echo "# Auto-generated by extract-warp-token.sh" >> "$ENV_FILE"
    echo "# This token expires and will need to be refreshed periodically" >> "$ENV_FILE"
    echo "WARP_TOKEN=$ID_TOKEN" >> "$ENV_FILE"
fi

echo ""
echo "✅ Success! Token saved to $ENV_FILE"
echo ""
echo "📝 Next steps:"
echo "   1. The token is now in your .env file"
echo "   2. Start the server with: bun run dev"
echo "   3. The token will expire after a few hours"
echo "   4. When it expires, run this script again to refresh it"
echo ""
echo "⚠️  Important:"
echo "   - Keep your .env file secret (it's already in .gitignore)"
echo "   - Don't commit tokens to version control"
echo "   - Share the .env.example file instead"
echo ""
